# Copyright 2026 [Angelo Ayton]
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import time
import json
import os
import sys
import select
import tty
import termios
from datetime import datetime
from dotenv import load_dotenv
from rich.live import Live
from rich.layout import Layout
from rich.panel import Panel
from rich.table import Table
from rich.console import Console
from rich.syntax import Syntax
from rich.text import Text
from rich import box

# --- IMPORTS ---
try:
    from src.core import scan_packet
except ImportError:
    print("❌ CRITICAL ERROR: Could not import 'src.core'.")
    sys.exit(1)

# --- CONFIG ---
load_dotenv()
HOST = os.getenv("HOST_NAME", "home.alpine.vm")
DATA_FILE = "data/simulation_traffic.json"
MODEL_NAME = "Gemini 3 Flash Preview" 

# --- KEYBOARD DRIVER ---
class InputListener:
    def __init__(self):
        self.fd = sys.stdin.fileno()
        self.old_settings = termios.tcgetattr(self.fd)
    def __enter__(self):
        tty.setcbreak(self.fd)
        return self
    def __exit__(self, type, value, traceback):
        termios.tcsetattr(self.fd, termios.TCSADRAIN, self.old_settings)
    def get_key(self):
        if select.select([sys.stdin], [], [], 0) == ([sys.stdin], [], []):
            ch = sys.stdin.read(1)
            if ch == '\x1b': 
                seq = sys.stdin.read(2)
                if seq == '[A': return 'UP'
                if seq == '[B': return 'DOWN'
                return None
            return ch
        return None

# --- DATA LOADER ---
def load_data():
    if not os.path.exists(DATA_FILE): return []
    try:
        with open(DATA_FILE, 'r') as f: return json.load(f)
    except: return []

# --- REPORT GENERATOR ---
def export_report(buffer, console):
    """Generates a professional HTML report and JSON log for stakeholders."""
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    
    # 1. JSON Export (Raw Data)
    json_filename = f"scan_log_{timestamp}.json"
    with open(json_filename, 'w') as f:
        json.dump(buffer, f, indent=2)
    
    # 2. HTML Export (Visual Report)
    html_filename = f"scan_report_{timestamp}.html"
    
    # Create a full table (no scrolling limits)
    report_table = Table(title=f"SILENT LOBSTER // FORENSIC SCAN REPORT // {timestamp}", expand=True, header_style="bold cyan")
    report_table.add_column("TIMESTAMP", style="dim", width=18)
    report_table.add_column("AGENT ID", style="bold white", width=20)
    report_table.add_column("THREAT VECTOR", style="yellow")
    report_table.add_column("AI ANALYSIS", style="cyan")
    report_table.add_column("STATUS", justify="center")

    for p in buffer:
        result = p.get('scan_result', {})
        status = result.get('status', 'UNKNOWN')
        
        status_text = Text("CLEAN", style="green")
        if status == "BLOCKED":
            status_text = Text("BLOCKED", style="bold red reverse")
        elif status == "API_ERROR":
            status_text = Text("⚠ API FAIL", style="bold yellow reverse")
        elif status == "ERROR":
            status_text = Text("ERROR", style="red")

        ts = p.get('timestamp', "")
        
        # Add row to report
        report_table.add_row(
            ts, 
            p.get('agent_id', 'Unknown'), 
            p.get('type', 'N/A'),
            result.get('analysis', 'No Analysis'),
            status_text
        )

    # Re-save with the table injected using a temporary console for clean output
    temp_console = Console(record=True, width=120)
    temp_console.print(Panel(Text(f"GENERATED BY: {HOST}\nENGINE: {MODEL_NAME}", justify="center", style="dim white")))
    temp_console.print(report_table)
    temp_console.save_html(html_filename)
    
    return html_filename

# --- UI COMPONENTS ---
def make_layout():
    layout = Layout()
    layout.split_column(
        Layout(name="header", size=3),
        Layout(name="body", ratio=1),
        Layout(name="footer", size=3)
    )
    layout["body"].split_row(
        Layout(name="traffic", ratio=4),
        Layout(name="alert", ratio=6)
    )
    return layout

def render_traffic(packets, selected_index=None):
    table = Table(expand=True, box=None, show_header=True, header_style="bold cyan")
    table.add_column("TIMESTAMP", style="dim", width=10)
    table.add_column("AGENT ID", style="white", width=16)
    table.add_column("STATUS", width=12)
    
    VIEW_SIZE = 18
    if selected_index is None:
        if len(packets) > VIEW_SIZE:
            visible_packets = packets[-VIEW_SIZE:]
            start_offset = len(packets) - VIEW_SIZE
        else:
            visible_packets = packets
            start_offset = 0
    else:
        if selected_index > (VIEW_SIZE // 2):
            start_idx = selected_index - (VIEW_SIZE // 2)
            if start_idx + VIEW_SIZE > len(packets):
                start_idx = max(0, len(packets) - VIEW_SIZE)
        else:
            start_idx = 0 
        visible_packets = packets[start_idx : start_idx + VIEW_SIZE]
        start_offset = start_idx

    for i, p in enumerate(visible_packets):
        real_index = start_offset + i
        status_style, status_text = "dim yellow", "PENDING"
        if p.get('scanned') and 'scan_result' in p:
            result = p['scan_result']
            if result.get('status') == "BLOCKED":
                status_style, status_text = "bold red reverse", "⚠ BLOCKED"
            elif result.get('status') == "API_ERROR":
                status_style, status_text = "bold yellow reverse", "⚡ API DOWN"
            elif result.get('status') == "CLEAN":
                status_style, status_text = "green", "✔ CLEAN"
            else:
                status_style, status_text = "red", "ERROR"
        row_style = "bold white on blue" if (selected_index is not None and real_index == selected_index) else None
        ts = p.get('timestamp', "00:00:00")[11:19]
        table.add_row(ts, p.get('agent_id', 'Unknown'), Text(status_text, style=status_style), style=row_style)
        
    title = "📡 INCOMING TRAFFIC (LIVE)" if selected_index is None else f"📡 TRAFFIC LOG ({selected_index + 1}/{len(packets)})"
    return Panel(table, title=title, border_style="blue")

def render_alert(packet):
    if not packet or packet.get('scan_result', {}).get('status') == "CLEAN":
        if packet and packet.get('code_snippet') and packet.get('scanned'): pass 
        else:
            return Panel(Text("\n\nSYSTEM SECURE\nActive Monitoring: ON", justify="center", style="dim green"), title="🛡️ FORENSIC DETAIL", border_style="green")
    
    grid = Table.grid(expand=True)
    is_blocked = packet.get('scan_result', {}).get('status') == "BLOCKED"
    header_color = "red" if is_blocked else "green"
    header_title = "MALICIOUS PACKET INTERCEPTED" if is_blocked else "CODE PACKET ANALYZED"
    
    header_text = Text()
    header_text.append(f"{header_title}\n", style=f"bold {header_color} blink" if is_blocked else f"bold {header_color}")
    header_text.append(f"VECTOR: {packet.get('type', 'UNKNOWN')}\n", style="bold yellow")
    header_text.append("AI FORENSICS:\n", style="underline")
    analysis = packet.get('scan_result', {}).get('analysis', 'No Analysis')
    header_text.append(f"{analysis}\n", style="cyan")
    
    grid.add_row(header_text)
    grid.add_row(Text(" "))
    code_view = Syntax(packet.get('code_snippet', '# No Code'), "python", theme="monokai", line_numbers=True, word_wrap=True)
    grid.add_row(code_view)
    
    return Panel(grid, title="🚨 THREAT REPORT" if is_blocked else "📝 INSPECTION LOG", border_style=f"bold {header_color}")

def render_header():
    return Panel(Text("PROJECT LOBSTER // AGENTIC IMMUNE SYSTEM", justify="center", style="bold white on blue"))

def render_footer(status_msg, stats=None, ai_active=True, style="dim white"):
    ai_status = "[bold green]AI: ON[/bold green]" if ai_active else "[bold red]AI: OFF[/bold red]"
    stats_str = ""
    if stats:
        stats_str = f" | [cyan]API: {stats['api']}[/cyan] | [green]LOCAL: {stats['local']}[/green] | [yellow]SAVED: ~{stats['saved']} Tok[/yellow]"
    return Panel(Text.from_markup(f"Host: {HOST} | Engine: {MODEL_NAME} | {ai_status}{stats_str} | {status_msg}", style=style))

# --- MAIN ENGINE ---
def run():
    # --- FIX: ENABLE RECORDING FOR EXPORT ---
    console = Console(record=True) 
    
    layout = make_layout()
    data = load_data()

    if not data:
        console.print("[bold red]Error: data/threat_db.json missing.[/bold red]")
        return

    with InputListener() as kb:
        while True: 
            buffer = []
            sim_complete = False
            paused = False
            
            ai_active = True
            stats = {'api': 0, 'local': 0, 'saved': 0}
            
            layout["header"].update(render_header())
            layout["body"]["traffic"].update(Panel(Text("\n\nREADY TO INITIALIZE\n\n[S] START SIMULATION\n[A] TOGGLE AI\n[Q] QUIT", justify="center", style="bold white"), title="STANDBY"))
            layout["body"]["alert"].update(Panel(Text("", justify="center"), title="OFFLINE"))
            layout["footer"].update(render_footer("Status: STANDBY | Waiting for Command...", stats=stats, ai_active=ai_active))

            with Live(layout, refresh_per_second=10, screen=True) as live:
                started = False
                while not started:
                    key = kb.get_key()
                    if key:
                        if key.lower() == 's': started = True
                        elif key.lower() == 'q': return
                        elif key.lower() == 'a': 
                            ai_active = not ai_active
                            layout["footer"].update(render_footer("Status: STANDBY | Waiting for Command...", stats=stats, ai_active=ai_active))
                    time.sleep(0.05)

                for i, packet in enumerate(data):
                    key = kb.get_key()
                    if key:
                        if key.lower() == 'q': sim_complete = True; break
                        if key.lower() == 'r': break 
                        if key.lower() == 'e': 
                             fname = export_report(buffer, console)
                             layout["footer"].update(render_footer(f"REPORT SAVED: {fname}", ai_active=ai_active, style="bold green"))
                             time.sleep(1.5)
                        if key.lower() == 'a':
                             ai_active = not ai_active
                             layout["footer"].update(render_footer(f"RUNNING | Packet {i+1}/{len(data)} | [SPACE] Pause [Q] Cancel", stats=stats, ai_active=ai_active))
                        if key == ' ': paused = not paused

                    while paused:
                        layout["footer"].update(render_footer("PAUSED ([SPACE] Resume | [R] Restart | [E] Export | [A] Toggle AI)", stats=stats, ai_active=ai_active, style="bold yellow"))
                        live.refresh()
                        p_key = kb.get_key()
                        
                        if p_key:
                            if p_key == ' ': paused = False
                            elif p_key == 'r': break 
                            elif p_key == 'q': sim_complete = True; paused = False; break
                            elif p_key.lower() == 'a':
                                 ai_active = not ai_active
                                 layout["footer"].update(render_footer("PAUSED ([SPACE] Resume | [R] Restart | [E] Export | [A] Toggle AI)", stats=stats, ai_active=ai_active, style="bold yellow"))
                            elif p_key.lower() == 'e':
                                 fname = export_report(buffer, console)
                                 layout["footer"].update(render_footer(f"REPORT SAVED: {fname}", ai_active=ai_active, style="bold green"))
                                 time.sleep(1.5)
                        
                        time.sleep(0.1)
                    
                    if key == 'r' or (key and key.lower() == 'r'): break 
                    if sim_complete: break

                    packet['scanned'] = False
                    buffer.append(packet)
                    layout["footer"].update(render_footer(f"RUNNING | Packet {i+1}/{len(data)} | [SPACE] Pause [Q] Cancel", stats=stats, ai_active=ai_active))
                    layout["body"]["traffic"].update(render_traffic(buffer))
                    layout["body"]["alert"].update(render_alert(None))
                    
                    for _ in range(1): # Minimal tick for UI stability
                        time.sleep(0.01)
                        if kb.get_key() == ' ': paused = True; break 

                    if paused: continue 

                    # Context Logic: Get last 3 packets (EXCLUDING CURRENT)
                    # buffer[:-1] gets all previous packets. [-3:] gets the last 3 of those.
                    context_history = buffer[:-1][-3:] if len(buffer) > 1 else []
                    
                    result = scan_packet(packet, context_history=context_history, use_llm=ai_active)
                    
                    # Update Stats
                    src = result.get('source', 'UNKNOWN')
                    if src == 'GEMINI_API':
                        stats['api'] += 1
                    elif src in ['IRON_DOME', 'GREEN_DOME', 'VAULT', 'CACHE', 'TEXT']:
                        stats['local'] += 1
                        stats['saved'] += 150 # Est. tokens per request
                        
                    packet['scan_result'] = result
                    packet['scanned'] = True
                    layout["body"]["traffic"].update(render_traffic(buffer))
                    
                    if result.get('status') == "BLOCKED":
                        layout["body"]["alert"].update(render_alert(packet))
                        for _ in range(40):
                            if kb.get_key(): break 
                            time.sleep(0.1)
                    else:
                        time.sleep(0.1)

                key = kb.get_key()
                if key == 'r': continue

                sim_complete = True
                layout["footer"].update(render_footer("COMPLETE | [UP/DOWN] Review | [E] Export Report | [R] Restart | [Q] Quit", stats=stats, ai_active=ai_active, style="bold green"))
                selected_index = len(buffer) - 1
                
                while True:
                    layout["body"]["traffic"].update(render_traffic(buffer, selected_index))
                    layout["body"]["alert"].update(render_alert(buffer[selected_index]))
                    live.refresh()
                    
                    r_key = kb.get_key()
                    if r_key == 'UP':
                        if selected_index > 0: selected_index -= 1
                    elif r_key == 'DOWN':
                        if selected_index < len(buffer) - 1: selected_index += 1
                    elif r_key == 'r': break 
                    elif r_key == 'e':
                        fname = export_report(buffer, console)
                        layout["footer"].update(render_footer(f"SUCCESS: Saved to {fname}", stats=stats, ai_active=ai_active, style="bold green on white"))
                        time.sleep(2.0)
                        layout["footer"].update(render_footer("COMPLETE | [UP/DOWN] Review | [E] Export Report | [R] Restart | [Q] Quit", stats=stats, ai_active=ai_active, style="bold green"))
                    elif r_key == 'q': return
                    time.sleep(0.05)

if __name__ == "__main__":
    try:
        run()
    except KeyboardInterrupt:
        pass
